// Generated by CoffeeScript 2.0.2
var DB, db, path;

({DB} = require('./db.js'));

path = require('path');

db = new DB(path.resolve(__dirname, '../data'));

db.add('lalka', 'lolka');

db.write();

console.log(db);
