// Generated by CoffeeScript 2.0.2
var DB, PORT, app, db, express, path;

({DB} = require('./db.js'));

path = require('path');

express = require('express');

app = express();

db = new DB(path.resolve(__dirname, '../data'));

app = express();

PORT = process.env.PORT || 3000;

app.get('/:num', function(req, res) {
  var file;
  file = db.files[req.params.num];
  if (file) {
    return res.send(file);
  } else {
    return res.sendStatus(404);
  }
});

app.listen(3000, function() {
  return console.log('Example app listening on port 3000!');
});
